INFRASTRUCTURE = [
    {"id": "port-suez", "type": "port", "label": "Port Suez", "lat": 29.97, "lng": 32.55, "country": "Egypt", "criticality": 0.9},
    {"id": "port-hormuz", "type": "port", "label": "Strait of Hormuz (Bandar Abbas)", "lat": 27.18, "lng": 56.28, "country": "Iran", "criticality": 0.9},
    {"id": "port-malacca", "type": "port", "label": "Strait of Malacca", "lat": 3.0, "lng": 100.5, "country": "Malaysia", "criticality": 0.9},
    {"id": "port-singapore", "type": "port", "label": "Port of Singapore", "lat": 1.264, "lng": 103.84, "country": "Singapore", "criticality": 0.8},
    {"id": "port-rotterdam", "type": "port", "label": "Port of Rotterdam", "lat": 51.92, "lng": 4.48, "country": "Netherlands", "criticality": 0.7},
    {"id": "port-shanghai", "type": "port", "label": "Port of Shanghai", "lat": 31.23, "lng": 121.47, "country": "China", "criticality": 0.8},
    {"id": "port-ningbo", "type": "port", "label": "Port of Ningbo-Zhoushan", "lat": 29.87, "lng": 121.54, "country": "China", "criticality": 0.7},
    {"id": "port-houston", "type": "port", "label": "Port of Houston", "lat": 29.74, "lng": -95.18, "country": "United States", "criticality": 0.7},
    {"id": "port-losangeles", "type": "port", "label": "Port of Los Angeles", "lat": 33.73, "lng": -118.27, "country": "United States", "criticality": 0.7},
    {"id": "port-jebelali", "type": "port", "label": "Port of Jebel Ali", "lat": 24.98, "lng": 55.06, "country": "UAE", "criticality": 0.7},
    {"id": "port-zhanjiang", "type": "port", "label": "Naval Base Zhanjiang", "lat": 21.16, "lng": 110.35, "country": "China", "criticality": 0.5},
    {"id": "port-vladivostok", "type": "port", "label": "Naval Base Vladivostok", "lat": 43.12, "lng": 131.89, "country": "Russia", "criticality": 0.5},
    {"id": "port-hamburg", "type": "port", "label": "Port of Hamburg", "lat": 53.54, "lng": 9.97, "country": "Germany", "criticality": 0.5},
    {"id": "port-antwerp", "type": "port", "label": "Port of Antwerp-Bruges", "lat": 51.27, "lng": 4.34, "country": "Belgium", "criticality": 0.5},
    {"id": "port-tanjung", "type": "port", "label": "Port of Tanjung Pelepas", "lat": 1.36, "lng": 103.55, "country": "Malaysia", "criticality": 0.6},
    {"id": "base-norfolk", "type": "military", "label": "Naval Station Norfolk", "lat": 36.95, "lng": -76.32, "country": "United States", "criticality": 0.6},
    {"id": "base-guam", "type": "military", "label": "Andersen AFB / Naval Guam", "lat": 13.58, "lng": 144.92, "country": "Guam", "criticality": 0.6},
    {"id": "base-diego", "type": "military", "label": "Diego Garcia", "lat": -7.31, "lng": 72.41, "country": "British Indian Ocean Territory", "criticality": 0.5},
    {"id": "base-taranto", "type": "military", "label": "Naval Base Taranto", "lat": 40.47, "lng": 17.23, "country": "Italy", "criticality": 0.4},
    {"id": "base-sevastopol", "type": "military", "label": "Sevastopol Naval Base", "lat": 44.6, "lng": 33.53, "country": "Ukraine", "criticality": 0.6},
    {"id": "base-yokosuka", "type": "military", "label": "Yokosuka Naval Base", "lat": 35.29, "lng": 139.66, "country": "Japan", "criticality": 0.6},
    {"id": "base-busan", "type": "military", "label": "Naval Base Busan", "lat": 35.1, "lng": 129.06, "country": "South Korea", "criticality": 0.5},
    {"id": "base-peterhead", "type": "military", "label": "RAF Lossiemouth", "lat": 57.72, "lng": -3.28, "country": "United Kingdom", "criticality": 0.4},
    {"id": "base-alameda", "type": "military", "label": "Naval Air Station Alameda", "lat": 37.79, "lng": -122.31, "country": "United States", "criticality": 0.4},
    {"id": "base-kaliningrad", "type": "military", "label": "Baltiysk Naval Base", "lat": 54.64, "lng": 19.91, "country": "Russia", "criticality": 0.5},
    {"id": "pipeline-nordstream", "type": "pipeline", "label": "Nord Stream", "lat": 55.35, "lng": 18.3, "country": "Baltic Sea", "criticality": 0.8},
    {"id": "pipeline-turkstream", "type": "pipeline", "label": "TurkStream", "lat": 42.0, "lng": 30.5, "country": "Black Sea", "criticality": 0.7},
    {"id": "pipeline-druzhba", "type": "pipeline", "label": "Druzhba", "lat": 52.4, "lng": 30.4, "country": "Belarus/Russia", "criticality": 0.7},
    {"id": "pipeline-keystone", "type": "pipeline", "label": "Keystone XL", "lat": 45.0, "lng": -101.0, "country": "United States", "criticality": 0.5},
    {"id": "pipeline-tapi", "type": "pipeline", "label": "TAPI", "lat": 33.5, "lng": 64.0, "country": "Afghanistan", "criticality": 0.6},
    {"id": "cable-flags", "type": "cable", "label": "FLAG Europe-Asia", "lat": 30.0, "lng": 40.0, "country": "Mediterranean", "criticality": 0.7},
    {"id": "cable-seamewe", "type": "cable", "label": "SeaMeWe-3", "lat": 15.0, "lng": 65.0, "country": "Indian Ocean", "criticality": 0.8},
    {"id": "cable-tat14", "type": "cable", "label": "TAT-14 (transatlantic)", "lat": 45.0, "lng": -40.0, "country": "Atlantic", "criticality": 0.8},
    {"id": "cable-mars", "type": "cable", "label": "MAREA", "lat": 38.0, "lng": -55.0, "country": "Atlantic", "criticality": 0.8},
    {"id": "chokepoint-gibraltar", "type": "chokepoint", "label": "Strait of Gibraltar", "lat": 36.0, "lng": -5.4, "country": "Spain/Morocco", "criticality": 0.7},
    {"id": "chokepoint-bosphorus", "type": "chokepoint", "label": "Bosphorus", "lat": 41.1, "lng": 29.06, "country": "Turkey", "criticality": 0.7},
    {"id": "chokepoint-babalmandeb", "type": "chokepoint", "label": "Bab el-Mandeb", "lat": 12.6, "lng": 43.3, "country": "Yemen/Djibouti", "criticality": 0.8},
    {"id": "chokepoint-panama", "type": "chokepoint", "label": "Panama Canal", "lat": 9.08, "lng": -79.68, "country": "Panama", "criticality": 0.7},
    {"id": "chokepoint-suez-canal", "type": "chokepoint", "label": "Suez Canal", "lat": 30.5, "lng": 32.3, "country": "Egypt", "criticality": 0.9},
    {"id": "base-rhein", "type": "military", "label": "Ramstein Air Base", "lat": 49.44, "lng": 7.6, "country": "Germany", "criticality": 0.6},
]
